name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: ["ubuntu-latest"]


    steps:
    # - uses: actions/checkout@v4
    # - name: Build the Docker image
    #   run: | 
    #     docker build . --file Dockerfile --tag my-dockerized-node-app:$(date +%s)

    - uses : mr-smithers-excellent/docker-build-push@v6
      name : Build and Push Docker Images To Docker Hub 
      with:  
        image: autobot26/docker-images
        tags: v1, latest
        dockerfile : ../../Dockerfile.ci
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
          

    
